"""Initial migration.

Revision ID: 9cf5af170308
Revises: 
Create Date: 2021-09-16 06:16:51.650560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cf5af170308'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history_password', 'user_id',
               existing_type=postgresql.UUID(),
               comment='Идентификатор пользователя',
               existing_nullable=False)
    op.alter_column('sessions', 'user_id',
               existing_type=postgresql.UUID(),
               comment='Идентификатор пользователя',
               existing_nullable=False)
    op.alter_column('sessions', 'token',
               existing_type=sa.VARCHAR(length=1000),
               comment='Токен пользователя',
               existing_nullable=False)
    op.alter_column('sessions', 'expires',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата конца времени жизни токена',
               existing_nullable=False)
    op.alter_column('users', 'blocked',
               existing_type=sa.BOOLEAN(),
               comment='Заблокированно?',
               existing_comment='Удалено?',
               existing_nullable=False)
    op.alter_column('users', 'is_new',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Новый пользователь?',
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_new',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Новый пользователь?',
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'blocked',
               existing_type=sa.BOOLEAN(),
               comment='Удалено?',
               existing_comment='Заблокированно?',
               existing_nullable=False)
    op.alter_column('sessions', 'expires',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата конца времени жизни токена',
               existing_nullable=False)
    op.alter_column('sessions', 'token',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='Токен пользователя',
               existing_nullable=False)
    op.alter_column('sessions', 'user_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='Идентификатор пользователя',
               existing_nullable=False)
    op.alter_column('history_password', 'user_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='Идентификатор пользователя',
               existing_nullable=False)
    # ### end Alembic commands ###
